export {
  type CoachCertificationInput,
  type CreateCoachDTO,
  CreateCoachSchema,
  type GetCoachByIdOrSlugDTO,
  GetCoachByIdOrSlugSchema,
  type ListCoachCardMediaDTO,
  ListCoachCardMediaSchema,
  type ListCoachCardMetaDTO,
  ListCoachCardMetaSchema,
  type ListCoachesDTO,
  ListCoachesSchema,
  type UpdateCoachDTO,
  UpdateCoachSchema,
} from "./coach.dto";
